# SwiftLint配置文件

# 包含的路径
included:
  - MacScreenCapture

# 排除的路径
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

# 禁用的规则
disabled_rules:
  - trailing_whitespace
  - todo
  - line_length

# 可选规则
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 规则配置
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# 自定义规则
custom_rules:
  # 强制使用 self
  explicit_self:
    name: "Explicit Self"
    regex: '(?<!self\.)\b(init|deinit)\b'
    message: "Use explicit self when calling init or deinit"
    severity: warning

  # 禁止使用 print
  no_print:
    name: "No Print"
    regex: '\bprint\s*\('
    message: "Use proper logging instead of print"
    severity: warning

  # 强制使用 weak self
  weak_self:
    name: "Weak Self"
    regex: '\[(?!weak\s+self)\s*self\s*\]'
    message: "Use [weak self] to avoid retain cycles"
    severity: warning

# 报告格式
reporter: "xcode"